config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  root to: 'works#index'
  resources :contacts, only: [:new, :create]
  resources :blogs, except: :index
  resources :works do
    collection do
      get 'works' 
    end
    member do
      get 'zoom'
    end
    member do
      get 'creater'
    end
    member do
      get 'types'
    end
    member do
      get 'creater_type'
    end
    collection do
      get 'profile'
    end
    collection do
      get 'contact'
    end
    collection do
      get 'link'
    end
    collection do
      get 'list'
    end
    collection do
      get 'show_mail'
    end
  end
end

app/models/work.rb
class Work < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  validates :title,        presence: true
  validates :artist_id,    numericality: { other_than: 0} 
  validates :type_id,      numericality: { other_than: 0} 

  has_many_attached :images
  belongs_to_active_hash :type
  belongs_to_active_hash :creater
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :contact_form, :description

  def index
    @work = "1z0jPhBvysuBn4MmX73UWNTo0THdb6Tml"
    @info = "News"
    @blogslist = Blog.page(params[:index]).per(30).order('created_at DESC')
    @blogs = Blog.page(params[:contents]).per(6).order('created_at DESC')
    @switch = judge_ip_switch
    if request.xhr?
      if params.has_key?(:index)
        render "blog_lists"
      elsif params.has_key?(:contents)
        render "blog_contents"
      end
    end
  end

  def new
    judge_ip
    @work = "1z0jPhBvysuBn4MmX73UWNTo0THdb6Tml"
    @workbox = Work.new
  end

  def create
    @workbox = Work.new(work_params)
    google_url_change
    if @workbox.save
    else
      render :new
    end
  end

  def edit
    @workbox = Work.find(params[:id])
  end

  def update
    @workbox = Work.find(params[:id])
    @upwork = params[:work]
    params_url_change
    if @workbox.update(work_params)
      if params[:work].has_key?(:image_ids)
        params[:work][:image_ids].each do |image_id|
          image = @workbox.images.find(image_id)
          image.purge
        end
      end
      redirect_to work_path(@workbox.id)
    else
      render :edit
    end
  end

  def destroy
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to action: :list
  end

  def works
    if params.has_key?(:back) #atist別でshowからもどるとき
      @creater_id = params[:back].to_i
      @info = Creater.find(@creater_id).name
      @workslist = Work.page(params[:index]).per(21).where("artist_id != 3 and artist_id != 8").order('created_year DESC')
      @works = Work.page(params[:contents]).per(21).where("artist_id = #{@creater_id}" ).order('created_year DESC')
      @body_info = "#{ @info } Works"
      @creaters = Creater.all
      @type = Type.all
      @artist_search = 1
    else #通常の遷移
      @type = Type.all
      @creaters = Creater.all
      @info = "Works"
      @workslist = Work.page(params[:index]).per(21).where("artist_id != 3 and artist_id != 8").order('created_year DESC')
      @works = Work.page(params[:contents]).per(21).where("artist_id != 3 and artist_id != 8").order('created_year DESC')
      @body_info = "All Works"
      @artist_search = 0
    end

    if request.xhr? #非同期通信時
      if params.has_key?(:index)
        render "lists"
      elsif params.has_key?(:contents)
        render "contents"
      else
        render "creater"
      end
    end
  end

  def creater
    if params[:id] == "3" || params[:id] == "8"
      @kinari = true
    else
      @kinari = false
    end
    @type = Type.all
    @creaters = Creater.all
    @info = Creater.find(params[:id]).name
    @works = Work.where(artist_id: params[:id]).page(params[:contents]).per(21).order('created_year DESC')
    @body_info = "#{@info} Works"
    @creater_id = params[:id]
    @artist_search = 1

    if params.has_key?(:contents)
      render 'contents'
    else
      render 'creater'
    end
  end

  def types
    if params[:id].to_i == 0
      @info = "All Works"
      @works = Work.page(params[:contents]).per(21).order('created_year DESC')
    else
      @info = Type.find(params[:id]).name
      @works = Work.where(type_id: params[:id]).page(params[:contents]).per(21).order('created_year DESC')
    end
    @body_info = "#{@info}"
    render 'creater'
  end

  def creater_type
  end

  def show
    @creater_id = params[:creater]
    @workslist = Work.page(params[:index]).per(21).order('created_year DESC')
    @item = Work.find(params[:id])
    @work = Work.find(params[:id]).image
    @creater = Creater.find(@item.artist_id).name
    @info = @item.title
    serch = params[:serch].to_i

    if serch == 1
      @artist_search = 1
    else
      @artist_search = 0
    end

    if request.xhr?
      if params.has_key?(:index)
        render "lists"
      end
    end
  end

  def zoom
    @item = Work.find(params[:id])
    @info = @item.title
  end

  def profile
    @work = "1z0jPhBvysuBn4MmX73UWNTo0THdb6Tml"
    @info = "Profile"
  end

  def contact
    @work = "1z0jPhBvysuBn4MmX73UWNTo0THdb6Tml"
    @info = "Contact"
  end
  
  def link
    @work = "1z0jPhBvysuBn4MmX73UWNTo0THdb6Tml"
    @info = "Link"
  end

  def list
    judge_ip
    @work = "1z0jPhBvysuBn4MmX73UWNTo0THdb6Tml"
    @workslist = Work.page(params[:list]).per(1).order('created_year DESC')
  end

  def show_mail
    judge_ip
    @mails = Contact.page(params[:mail]).per(25).order('created_at DESC')
  end

  private

  def work_params
    params.require(:work).permit(:title,:image,:image2,:image3,:image4,:image5,:image6,:image7,:image8,:image9,:image10,:description,:youtube,:created_year,:artist_id,:type_id,images:[])
  end

  def params_url_change
    @upwork[:youtube].slice!("https://www.youtube.com/watch?v=")
  end

  def image_delete
    
  end
  
  def google_url_change
    @workbox.youtube.slice!("https://www.youtube.com/watch?v=")
  end

  def client_ip
    request.ip
  end

  def judge_ip
    if client_ip == "::1"
    elsif client_ip == ENV["IP_ADDRESS"]
    else
      redirect_to root_path
    end
  end

  def judge_ip_switch
    if client_ip == "::1"
      true
    elsif client_ip == ENV["IP_ADDRESS"]
      true
    else
      false
    end
  end

  def contact_form
    @contact = Contact.new
    @ip = request.ip
  end

  def description
    @description = "コマドリハウスとは創作活動を行うアーティストグループです。もともとは、コマドリアニメーションを制作するグループから始まりました。人の活動は全てが表現活動であり、社会的な行動だと言えます。どんな人でもアーティストでありうると私たちは考えています。現在、コマドリハウスではアニメーションのみならず、日常生活で生まれるイラスト、デザイン、WEBアプリケーション制作、彫刻、絵画など様々な制作活動を行っています。"
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_art_form.html.erb
<%= form_with(model: workbox, data: { remote: false}) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="works-form">
    <%= f.label "作品名",for:"title" %><span class="emphasis">必須</span>
    <%= f.text_area :title, class:"works-text", id:"image" ,placeholder:"作品の題名" %>
    <%= f.label "作品の説明",for:"description" %>
    <%= f.text_area :description, class:"works-text", id:"text" ,placeholder:"作品の説明" %>
    <%= f.label "Youtubeのリンク",for:"youtube" %>
    <%= f.text_area :youtube, class:"works-text", id:"form-youtube" ,placeholder:"youtubeのリンク" %>
    <p id="blog-new-info">作品情報編集時、削除したい画像はチェック入をれる</p>
    <div id="attached-image">
        <% workbox.images.each do |image| %>
          <div class="attached-image-box">
            <%= f.check_box :image_ids, {:multiple => true,:class => "image-check"}, image.id, false %>
            <%= image_tag image, :size=>"100x100" %> <br>
          </div>
          <%= f.hidden_field :images, multiple: true, value: image.signed_id %>
        <% end %>
      </div>
    <p>画像の追加</p>
    <%= f.label :images %>
    <%= f.file_field :images ,multiple: true %>
      <div class="inner-box">
        <%= f.label "制作年",for:"created_year" %> 
        <%= f.text_field :created_year, class:"works-text", id:"year" ,placeholder:"2021", maxlength:"4" %>
      </div>
      <div class="inner-box">
        <%= f.label "作者名",for:"artist_id" %><span class="emphasis">必須</span>
        <%= f.collection_select(:artist_id, Creater.all, :id, :name, {}, {class:"works-text", id:"artist"}) %>
      </div>
      <div class="inner-box">
        <%= f.label "ジャンル",for:"type_id" %><span class="emphasis">必須</span>
        <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"works-text", id:"type-id"}) %>  
      </div>
    </div>
    <%= f.submit "作品を登録" ,class:"works-text" %>
  </div>
<% end %>

app/views/works/_blog_contents.html.erb
<% @blogs.each do |blog| %>
    <div class="blog-head">
      <div class="blog-date">
        <%= blog.created_at.to_s(:date_jp) %>
      </div>
      <div class="blog-share">
        Shere.
        <%= link_to image_tag('facebook.png', class:"sns-rogo"),"http://www.facebook.com/share.php?u=#{request.url}",target: '_blank' %>
        <%= link_to image_tag('twitter.png', class:"sns-rogo"),"https://twitter.com/share?url=#{request.url}&text=#{blog.title}&hashtags=コマドリハウス",target: '_blank' %>
        <% if @switch %>
          <div class="edit-menu">
            <%= link_to 'Edit' ,edit_blog_path("#{blog.id}"),class:"edit-btn" %>
            <%= link_to 'Delete' ,blog_path("#{blog.id}") ,method: :delete, class:"delete-btn" %>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to(blog_path(blog.id) , remote: false ) do %>
      <div class="blog-title">
        <%= blog.title %>
      </div>
      <% blog.blog_images.each do |image| %>
          <%= image_tag(image, class:"blog-image") %>
      <% end %>
      <div class="blog-text">
        <%= blog.text_1 %>
      </div>
    <% end %>
    <%= link_to blog.text_2,blog.image_2, target: :_blank %>
    <div class="profile-border">
    </div>
<% end %>

app/views/works/blog_contents.js.erb
$('#news-contents').append("<%= escape_javascript(render partial: "blog_contents" ) %>");

$('#more-contents').remove();
$("#next-contents").append("<%= escape_javascript(
  link_to_next_page(@blogs, '過去の記事をさらに表示', remote: true, id: 'more-contents',:param_name => "contents" )
) %>");

app/views/works/contents.js.erb
$('#contents-body').append("<%= escape_javascript(render 'shared/contents-body') %>");
$('#artists-list').slideUp(100);
$('#type-list').slideUp(100);

$('#more-contents').remove();
$("#next-contents").append("<%= escape_javascript(
  link_to_next_page(@works, 'さらに見る', remote: true, id: 'more-contents',:param_name => "contents" )
) %>");

$('#body-info').text("<%= escape_javascript(@body_info) %>");

app/views/works/creater.js.erb
$('.content').remove();
$('#contents-body').append("<%= escape_javascript(render 'shared/contents-body') %>");
$('#artists-list').slideUp(100);
$('#type-list').slideUp(100);

$('#more-contents').remove();
$("#next-contents").append("<%= escape_javascript(
  link_to_next_page(@works, 'さらに見る', remote: true, id: 'more-contents',:param_name => "contents" )
) %>");

$('#body-info').text("<%= escape_javascript(@body_info) %>");

app/views/works/each-creater.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>
<div class="body">
  <%# ここから左辺の目次欄 %>
  <%= render "shared/works_index"%>
  <%# ここからメインコンテンツ表示域 %>
  <div class="works-contents">
    <div class="selected-works">
      All Works<div class="each-menu"><%= render 'shared/each-menu' %></div>
    </div>
    
      <%= render 'shared/contents-body'%>

   </div>
</div>
<div class="footer-area">
  <%= render "shared/footer"%>
</div>

app/views/works/edit.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>
<div class="form-body">
  登録情報の編集
    <%= render partial: "art_form", locals:{ workbox: @workbox } %>
</div>

app/views/works/index.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>
<div class="news-body">
  <div id="news-index-box">
    <%# ここから左辺の目次欄 %>
    <div class="index">
      <div class="index-title">
        News Index
      </div>
      <div class="index-contents">
          <%= render "shared/news_index"%>
        <div id="more-lists">
        </div>
      </div>
      <div id="next">
        <%= link_to_next_page @blogslist,'過去の記事を表示', :param_name => 'index' , remote: true, id: 'more-index'%>      
      </div>
    </div>
  </div>
  <%# ここからNews記事表示域 %>
  <div id="right-view">
    <div id="news-contents">
      <%= render partial: "blog_contents" %>
    </div>
    <div id="next-contents" class="more-blog">
      <%= link_to_next_page @blogs,'過去の記事を表示', :param_name => 'contents' , remote: true, id: 'more-contents'%>
    </div>
    <div class="footer-area">
      <%= render "shared/footer"%>
    </div>
  </div>
</div>
<div id="page_top" style="display: none;">
  Page Top
</div>
<div id="mobile-block">
</div>

app/views/works/list.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>
<div class="work-lists">
<div class="form-menu">
  <%= render "shared/form-menu" %>
</div>
  
    <% @workslist.each do |work| %>
      <div class="work">
        <div class="edit-works">
          <%= link_to "編集",edit_work_path(work.id) %>
        </div>
        <div class="delete-works">
          <%= link_to "削除",work_path(work.id),method: :delete %>
        </div>
        <div class="item id">
          <%= link_to Creater.find(work.artist_id).name ,edit_work_path(work.id) %>
        </div>
        <div class="item text">
          <%= link_to work.title ,edit_work_path(work.id) %><%= link_to work.created_year ,edit_work_path(work.id),class:"year" %>
        </div>
        <div class="item image">
            <% work.images.each_with_index do |image,i| %>
              <% if i == 0 %>
                <%= image_tag image,class:"item-image" %>
              <% end %>
            <% end %>
        </div>
        <div class="item">
          <div class="list-description-box">
            <%= link_to work.description ,edit_work_path(work.id) %>
          </div>
        </div>
      </div>
    <% end %>
  <div class="paginate-list">
    <%= paginate @workslist, :param_name => 'list' %>
  </div>
</div>
<div class="footer-area">
  <%= render "shared/footer"%>
</div>

app/views/works/new.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>
<div class="form-body">
<div class="form-menu">
  <%= render "shared/form-menu" %>
</div>
  作品登録
  <%= render partial: "art_form", locals:{ workbox: @workbox } %>
</div>

app/views/works/profile.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>
<div class="profile">
  <div id="about">
    <span class="text-title">
      <span class="brand">コマドリハウス</span>とは<br><br>
    </span>
    <span class="main-text">
      創作活動を行うアーティストグループです。<br>   
      もともとは、コマドリアニメーションを制作するグループ<br>から始まりました。
      人の活動は全てが表現活動であり、<br>社会的な行動だと言えます。<br>
      どんな人でもアーティストでありうると私たちは考えています。<br>
      現在、コマドリハウスではアニメーションのみならず、<br>日常生活で生まれる
      イラスト、デザイン、<br>WEBアプリケーション制作、彫刻、<br>絵画など様々な制作活動を行っています。<br>
    </span>
  </div>
  <div id="about-artists">
    <div id="artists-title-box">
      <div class="artists-title">
        Artists
      </div>
      <div id="artists-border">
      </div>
    </div>

    <div class="artist-profile">
      <div class="artist-head">
        <%= image_tag("takuya.png", class:"artist-image") %>
        <div class="artist-head-text profile-right">
          <div class="profile-name">
            おの たくや
          </div>
          <div class="artist-status">
            アニメーション、デザイン、彫刻、イラスト<br>
            Webアプリケーション開発などを行う。<br><br>
            2011年  NHKミニミニ映像大賞 入選<br>
            2006年  江戸川伝統工芸プロジェクト 銀賞<br>
          </div>
        </div>
      </div>
      <div class="artist-overview">
        東京造形大学 美術学科 彫刻専攻 卒業<br>
        2008年 私立 自由の森学園中学・高等学校で美術(木工)の実習助手を４年間担当<br>
        2013年 特定非営利活動法人 自立応援団で障害福祉事業に従事、現在に至る。<br>
        2021年 社会福祉士の国家資格を取得。
      </div>
    </div>

    <div class="profile-border">
    </div>

    <div class="artist-profile">
      <div class="artist-head">
        <div class="artist-head-text profile-left">
          <div class="profile-name">
          小野 惇子
          </div>
          <div class="artist-status">
          イラスト、絵画、デザイン、<br>彫刻作品などの制作を行う。<br>
          </div>  
        </div>
        <%= image_tag("atsuko.png", class:"artist-image image-right atsuko-image") %>
      </div>
      <div class="artist-overview">
        東京造形大学 美術学科 彫刻専攻 卒業<br>
      </div>
    </div>

    <div class="profile-border">
    </div>

    <div class="artist-profile">
      <div class="artist-head">
        <%= image_tag("kinari.png", class:"artist-image") %>
        <div class="artist-head-text profile-right">
          <div class="profile-name">
            Kinari
          </div>
          <div class="artist-status">
            昆虫や生物のイラストや<br>立体作品などを制作している。<br>
            オリジナルの妖怪を考案することもある。<br>
            現在小学５年生<br><br>
          </div>
        </div>
      </div>
      <div class="artist-overview">
        鯨、恐竜、昆虫、妖怪などあらゆる生物に興味をもっている。<br>
        昆虫は国産、外国産含め、現在20匹程を飼育、繁殖を行っている。<br>
        妖怪は、水木しげる にインスパイアされている。
      </div>
    </div>
    <div class="footer-area">
      <%= render "shared/footer"%>
    </div>
    <div id="mobile-block-pro">
    </div>
  </div>
</div>


<div id="page_top" style="display: none;">
  Page Top
</div>

app/views/works/show_mail.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>
<div class="work-lists">
<div class="form-menu">
  <%= render "shared/form-menu" %>
</div>
  
    <% @mails.each do |mail| %>
      <div class="work">
        <div class="item id">
          <%= mail.name %>
        </div>
        <div class="item text">
          <%= mail.email %>
        </div>
        <div class="item image">
          <%= mail.ip_address %>
        </div>
        <div class="item image">
          <%= mail.text %>
        </div>
        <div class="item">
          <div class="list-description-box">
            <%= mail.created_at %>
          </div>
        </div>
      </div>
    <% end %>
  <div class="paginate-list">
    <%= paginate @mails, :param_name => 'mail' %>
  </div>
</div>
<div class="footer-area">
  <%= render "shared/footer"%>
</div>

app/views/works/works.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>

<div class="body">
  <%# ここから左辺の目次欄 %>
  <%= render "shared/works_index"%>
  <%# ここからメインコンテンツ表示域 %>
  <div class="works-contents">
    <div class="selected-works" id="selected-works">
      <div id="body-info">
        <%= @body_info %>
      </div>
      <span class="artist-menu" id="artist-menu">
        アーティスト別
      </span>
      <span class="artist-menu" id="type-menu">
        カテゴリー別
      </span>
      <%= render 'shared/master-menu'%>
      <%= render 'shared/type-menu'%>
      <%= render 'shared/creater-type-menu'%>
    </div>
      
    <div class="contents-body" id="contents-body">
        <%= render 'shared/contents-body' %>
    </div>
    <div id="next-contents">
      <%= link_to_next_page @works,'もっと見る', :param_name => 'contents' , remote: true, id: 'more-contents'%>
    </div>
  
    <div class="footer-area">
      <%= render "shared/footer"%>
    </div>
  </div>
</div>
<div id="page_top" style="display: none;">
  Page Top
</div>

app/views/works/zoom.html.erb
<div class="header">
  <%= render "shared/frist-header"%>
</div>
<div id="work-right-view">
  <div class="works-info">
      Enlarged view
  </div>
  
  <div class="contents-body-show-zoom">
      <ul>
        <li class="work-image-list">
          <% if @item.images[1].present? %>
            <div id="slide-btn">
              <div id="left-btn">＜</div>
              <div id="right-btn">＞</div>
            </div>
          <% end %>
          <% @item.images.each_with_index do |image,i|%>
            <%= image_tag (image),class:"work-image" ,id:"img-#{i+1}"%>
          <% end %>
        </li>
      </ul>
  </div>

  <div class="footer-area">
    <%= render "shared/footer"%>
  </div>
</div>
<div id="page_top" style="display: none;">
  Page Top
</div>